FROM java:openjdk-8-jre-alpine

#install Spring Boot artifact

RUN mkdir -p /var/app/and-service-api

WORKDIR var/app/and-service-api

ADD build/libs/person-service-0.0.1-SNAPSHOT.jar andservice-read-api-0.0.1.jar

RUN sh -c 'touch /andservice-read-api-0.0.1.jar'

#profile is to passed Dynamically from Docker terminal (local,dev.....)

EXPOSE 8080

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/andservice-read-api-0.0.1.jar"]